<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GarasTransport.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GarasTransport.Domain\GarasTransport.Domain.csproj" />
    <ProjectReference Include="..\GarasTransport.Infrastructure\GarasTransport.Infrastructure.csproj" />
  </ItemGroup>

</Project>
